config/routes.rb
Gallery::Application.routes.draw do
  get "contact/index"
  get "commisions/index"
  get "about/index"
  get "welcome/index"
  resources :uploads
  
  root 'welcome#index'
  get :welcome, to: 'welcome#index', as: :home
  get :contact, to: 'contact#index', as: :contact
  get :about, to: 'about#index', as: :about
  get :commisions, to: 'commisions#index', as: :commisions
  get 'uploads/popup/:id', to: 'uploads#popup', as: :popup
  

end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commisions_controller.rb
class CommisionsController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :set_upload, only: [:show, :edit, :update, :destroy, :popup]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end
  
  # GET /uploads/popup/1
  def popup
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render action: 'show', status: :created, location: @upload }
      else
        format.html { render action: 'new' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:title, :description, :img, :uploaded)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commisions_helper.rb
module CommisionsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.haml
%h1 About#index
%p Find me in app/views/about/index.html.haml

app/views/commisions/index.html.haml
%h1 Commisions#index
%p Find me in app/views/commisions/index.html.haml

app/views/contact/index.html.haml
%h1 Contact#index
%p Find me in app/views/contact/index.html.haml

app/views/layouts/_nav.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "ARTIST", home_path, class: :brand
      .nav-collapse
        %ul.nav
          %li= link_to "Gallery", uploads_path
          %li= link_to "About", about_path
          %li= link_to "Commissions", commisions_path
          %li= link_to "Contact", contact_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gallery
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
  %body
    #nav= render "./layouts/nav"
    .container-fluid(data-pjax-container="true")= yield

app/views/uploads/_disqus.html.haml
#disqus_thread
:javascript
  /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
  var disqus_shortname = 'gallery-basil'; // required: replace example with your forum shortname

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
%noscript
  Please enable JavaScript to view the
  %a{href: "http://disqus.com/?ref_noscript"} comments powered by Disqus.
%a.dsq-brlink{href: "http://disqus.com"}
  comments powered by
  %span.logo-disqus Disqus

app/views/uploads/_form.html.haml
= form_for @upload do |f|
  - if @upload.errors.any?
    #error_explanation
      %h2= "#{pluralize(@upload.errors.count, "error")} prohibited this upload from being saved:"
      %ul
        - @upload.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :img
    = f.file_field :img
  .actions
    = f.submit 'Save'

app/views/uploads/edit.html.haml
%h1 Editing upload

= render 'form'

= link_to 'Show', @upload
\|
= link_to 'Back', uploads_path

app/views/uploads/index.html.haml
%h1 Listing uploads

- @uploads.each do |upload|
  = link_to popup_path(upload), class: :ajax_popup_link do
    = upload.title
  %br

.admin= link_to 'New Upload', new_upload_path

app/views/uploads/new.html.haml
%h1 New upload

= render 'form'

= link_to 'Back', uploads_path

app/views/uploads/popup.html.haml
.ajax-popup
  %p#notice= notice

  %p
    %h2= @upload.title
  
  %p
    temp image tag placeholder
    -# image_tag @upload.img
  
  %p
    = @upload.description
  
  = link_to :Show, @upload

app/views/uploads/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @upload.title
%p
  %b Description:
  = @upload.description
%p
  %b Img:
  = @upload.img
%p
  %b Uploaded:
  = @upload.uploaded

= link_to 'Edit', edit_upload_path(@upload)
\|
= link_to 'Back', uploads_path

= render "disqus"

app/views/welcome/index.html.haml
%h1 Hello there
%p Welcome on the gallery website of ARTIST! Here you will find much of his work. Have a look at his #{link_to "gallery", uploads_path} if you want to see his work!
%a.img{:href => image_path("rails.png")}
  %img{:src => image_path("rails.png"), :alt => "rails"}